'use strict';

define (function () {
	var constant = {
		
		SERVICE: 1,
		FELLOWSHIP: 2,
		OTHER: 4,
		FAMILY_EVENT: 4096,

		COMMUNITY: 8,
		CAMPUS: 16,
		FRATERNITY: 32,
		NATION: 64,
		FUNDRAISER: 128,
		GENERAL: 8192,
		//GENERAL_FELLOWSHIP: this.GENERAL,
		INTERCHAPTER_HOME: 256,
		CRAZY_FELLOWSHIP: 512,
		SEXY_FELLOWSHIP: 1024,
		COOL_FELLOWSHIP: 2048,
		MEETING: 16384,
		//GENERAL_EVENT: this.MEETING + this.OTHER,
		INTERCHAPTER_AWAY: 32768
		//INTERCHAPTER: this.INTERCHAPTER_HOME + this.INTERCHAPTER_AWAY

	};

	return constant;
});